config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contacts, only: [:index]
  namespace :contacts do
    resources :companies, except: [:index]
    resources :people, except: [:index]
  end

  get 'notes/new/:contact_id', to: 'notes#new_for_contact', as: 'new_note_for_contact'
  resources :notes do
    get :unassociated, on: :collection
  end
  resources :favorites

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

  root 'home#index'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  include PermitsAttributes

  belongs_to :user, inverse_of: :favorites

  validates :title, presence: true
  validates :url, presence: true
  validates :user, presence: true

  before_validation do
    if !self.url.blank? && !self.url.start_with?('http')
      self.url = 'http://' + self.url
    end
  end

  scope :search, ->(text) do
    where("LOWER(favorites.title) LIKE :search" +
            " OR LOWER(favorites.content) LIKE :search" +
            " OR LOWER(favorites.url) LIKE :search", search: "%#{text.downcase}%")
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  # GET /favorites
  # GET /favorites.json
  def index
    @favorites = current_user.favorites

    @search_scope = (search_in_params?) ? params[:options][:search].to_s : nil
    if @search_scope
      @favorites = @favorites.search(@search_scope)
    end

    @order_fields = %w(title url created_at)
    @selected_order = (order_in_params? && @order_fields.include?(params[:options][:order].to_s)) ? params[:options][:order].to_s : 'title'

    @sorts = %w(asc desc)
    @selected_sort = (sort_in_params? && @sorts.include?(params[:options][:sort].to_s)) ? params[:options][:sort].to_s : 'asc'

    #nullify empty string fields (but string type only)
    @favorites = if %w(title url).include?(@selected_order)
                   @favorites.order("NULLIF(#{@selected_order},'') #{@selected_sort} NULLS LAST")
                 else
                   @favorites.order("#{@selected_order} #{@selected_sort} NULLS LAST")
                 end

    @favorites = @favorites.page(params[:page])
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params.merge(user: current_user))

    respond_to do |format|
      if @favorite.save
        format.html do
          flash[:notice] = t('controllers.favorites.create.success')
          redirect_to @favorite
        end
        format.json { render :show, status: :created, location: @favorite }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html do
          flash[:notice] = t('controllers.favorites.update.success')
          redirect_to @favorite
        end
        format.json { render :show, status: :ok, location: @favorite }
      else
        format.html { render :edit }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: t('controllers.favorites.destroy.success') }
      format.json { head :no_content }
    end
  end

  private
  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  def favorite_params
    Favorite.permits_params(params.require(:favorite))
  end

  def search_in_params?
    options_params? && params[:options][:search] && !params[:options][:search].blank?
  end

  def order_in_params?
    options_params? && params[:options][:order] && !params[:options][:order].blank?
  end

  def sort_in_params?
    options_params? && params[:options][:sort] && !params[:options][:sort].blank?
  end

  def options_params?
    params && params[:options]
  end

end

app/views/favorites/_form.html.erb
<%= simple_form_for(@favorite) do |f| %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :url %>
      <%= f.input :content, input_html: {rows: 8} %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/favorites/edit.html.erb
<div class="content-box col-centered">
  <h2><%= t('views.favorites.edit.title') %></h2>

  <%= render 'form' %>

  <%= link_to t('views.favorites.edit.show_link'), @favorite %> |
  <%= link_to t('views.favorites.edit.back_list'), favorites_path %>
</div>

app/views/favorites/index.html.erb
<div class="content-box col-centered table-responsive">
  <h2><%= t('views.favorites.index.title') %></h2>

  <%= paginate @favorites %>
  <p class="pagination-total"><%= page_entries_info @favorites %></p>

  <div class="btn-group pull-right">
    <a href="<%= new_favorite_path %>" class="btn btn-primary">
      <span class="glyphicon glyphicon-plus"></span> <%= t('views.favorites.index.new_favorite') %>
    </a>
  </div>

  <%= simple_form_for(:options, method: :get, html: {class: 'filters_form'}) do |f| %>
      <%= f.input_field :search, required: false, value: @search_scope, placeholder: t('views.favorites.index.search') %>

      <br/>
      <label class="select required" for="options_order"><%= t 'views.favorites.index.sort_by' %></label>
      <% sortable_fields_collection = []
         @order_fields.each do |field|
           sortable_fields_collection << [t("views.favorites.index.sortable_fields.#{field}"), field]
         end
      %>
      <%= f.input_field :order, collection: sortable_fields_collection, selected: @selected_order %>

      <% sort_scopes_collection = []
         @sorts.each do |scope|
           sort_scopes_collection << [t("views.favorites.index.sorts.#{scope}"), scope]
         end
      %>
      <%= f.input_field :sort, collection: sort_scopes_collection, selected: @selected_sort %>
  <% end %>

  <table class="table table-condensed table-striped table-hover pretty-table">
    <thead>
    <tr>
      <th><%= t('views.favorites.index.title') %></th>
      <th><%= t('views.favorites.index.content') %></th>
      <th><%= t('views.favorites.index.url') %></th>
      <th><%= t('views.favorites.index.create_date') %></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @favorites.each do |favorite| %>
        <tr>
          <td><%= favorite.title %></td>
          <td class="long-text-cell"><%= favorite.content %></td>
          <td><%= link_to favorite.url, favorite.url, target: :blank %></td>
          <td><%= localize favorite.created_at, format: :short_date %></td>
          <td class="actions-cell"><%= actions_group edit_btn(edit_favorite_path(favorite)), delete_btn(favorite_path(favorite)) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @favorites %>
  <p class="pagination-total"><%= page_entries_info @favorites %></p>
</div>

app/views/favorites/new.html.erb
<div class="content-box col-centered">
  <h2><%= t('views.favorites.new.title') %></h2>
  <%= render 'form' %>

  <%= link_to t('views.favorites.new.back_list'), favorites_path %>
</div>

app/views/favorites/show.html.erb
<div class="content-box col-centered">
  <h2><%= @favorite.title %></h2>

  <p>
    <strong><%= t('views.favorites.show.title') %>:</strong>
    <%= @favorite.title %>
  </p>

  <p>
    <strong><%= t('views.favorites.show.content') %>:</strong>
    <%= @favorite.content %>
  </p>

  <p>
    <strong><%= t('views.favorites.show.url') %>:</strong>
    <%= link_to @favorite.url, @favorite.url, target: :blank %>
  </p>

  <%= link_to t('views.favorites.show.edit_link'), edit_favorite_path(@favorite) %> |
  <%= link_to t('views.favorites.show.back_list'), favorites_path %>
</div>