config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contacts, only: [:index]
  namespace :contacts do
    resources :companies, except: [:index]
    resources :people, except: [:index]
  end

  get 'notes/new/:contact_id', to: 'notes#new_for_contact', as: 'new_note_for_contact'
  resources :notes do
    get :unassociated, on: :collection
  end
  resources :favorites

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

  root 'home#index'
end

app/views/shared/_flash_msg.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= flash_msg_class(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_main_nav.html.erb
<li><%= link_to t('views.shared._main_nav.contacts'), contacts_path %></li>
<li><%= link_to t('views.shared._main_nav.notes'), notes_path %></li>
<li><%= link_to t('views.shared._main_nav.favorites'), favorites_path %></li>

app/views/shared/_user_nav.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <span class="username"><%= current_user.email %></span>
    <span class="caret"></span>
  </a>

  <ul class="dropdown-menu">
    <% if session.key?(:act_as) %>
        <li><%= link_to t('views.shared._user_nav.myself'), myself_again_users_path, method: :delete %></li>
    <% elsif current_user.has_role? :admin %>
        <li><%= link_to t('views.shared._user_nav.users'), users_path %></li>
    <% end %>

    <li><%= link_to t('views.shared._user_nav.my_account'), edit_user_registration_path %></li>
    <li><%= link_to t('views.shared._user_nav.log_out'), destroy_user_session_path, method: :delete %></li>
  </ul>
</li>