config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contacts, only: [:index]
  namespace :contacts do
    resources :companies, except: [:index]
    resources :people, except: [:index]
  end

  get 'notes/new/:contact_id', to: 'notes#new_for_contact', as: 'new_note_for_contact'
  resources :notes do
    get :unassociated, on: :collection
  end
  resources :favorites

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # GET /
  def index
  end

end

app/views/home/index.html.erb
<p class="text-center"><%= t('views.home.index.hello_user', email: current_user.email) %></p>

<% if !current_user.contacts.empty? %>
    <div class="col-sm-6 col-xs-12 home-box home-box-blue">
      <%= link_to t('views.home.index.contacts', count: current_user.contacts.count ), contacts_path %>
    </div>
    <div class="col-sm-3 col-xs-6 home-box home-box-lime">
      <%= link_to t('views.home.index.new_person'), new_contacts_person_path %>
    </div>
    <div class="col-sm-3 col-xs-6 home-box home-box-orange">
      <%= link_to t('views.home.index.new_company'), new_contacts_company_path %>
    </div>
<% else %>
    <div class="col-sm-6 col-xs-6 home-box home-box-lime">
      <%= link_to t('views.home.index.new_person'), new_contacts_person_path %>
    </div>
    <div class="col-sm-6 col-xs-6 home-box home-box-orange">
      <%= link_to t('views.home.index.new_company'), new_contacts_company_path %>
    </div>
<% end %>

<% if !current_user.notes.empty? %>
    <div class="col-sm-6 col-xs-12 home-box">
      <%= link_to t('views.home.index.notes', count: current_user.notes.count), notes_path %>
    </div>
    <div class="col-sm-6 col-xs-12 home-box home-box-blue">
      <%= link_to t('views.home.index.new_note'), new_note_path %>
    </div>
<% else %>
    <div class="col-sm-12 col-xs-12 home-box home-box-blue">
      <%= link_to t('views.home.index.new_note'), new_note_path %>
    </div>
<% end %>