config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :contacts, only: [:index]
  namespace :contacts do
    resources :companies, except: [:index]
    resources :people, except: [:index]
  end

  get 'notes/new/:contact_id', to: 'notes#new_for_contact', as: 'new_note_for_contact'
  resources :notes do
    get :unassociated, on: :collection
  end
  resources :favorites

  resources :users, only: [:index] do
    post 'act_as', on: :member
    delete 'myself_again', on: :collection
  end

  root 'home#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base

  include PermitsAttributes

  validates :user, presence: true
  validates :name, presence: true

  belongs_to :user, inverse_of: :contacts
  has_many :notes, inverse_of: :contact, dependent: :destroy

  scope :search, ->(text, search_in = [:name, :first_name, :email, :activity]) do
    where(search_in.map{|field| "LOWER(contacts.#{field}) LIKE :search"}.join(" OR "), search: "%#{text.downcase}%")
  end
end

app/models/contacts/company.rb
class Contacts::Company < Contact

  has_many :people, inverse_of: :company, class_name: Contacts::Person, dependent: :nullify

end

app/models/contacts/person.rb
class Contacts::Person < Contact

  belongs_to :company, inverse_of: :people, class_name: Contacts::Company

end

app/controllers/contacts/companies_controller.rb
class Contacts::CompaniesController < ContactsController

  # GET /contacts/companies/1
  # GET /contacts/companies/1.json
  def show
    @notes = @contact.notes
  end

  # GET /contacts/companies/new
  def new
    @contact = Contacts::Company.new
  end

  # GET /contacts/companies/1/edit
  def edit
  end

  # POST /contacts/companies
  # POST /contacts/companies.json
  def create
    @contact = Contacts::Company.new(contacts_company_params.merge(user: current_user))

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: t('controllers.contacts.companies.create.success') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/companies/1
  # PATCH/PUT /contacts/companies/1.json
  def update
    respond_to do |format|
      if @contact.update(contacts_company_params)
        format.html { redirect_to @contact, notice: t('controllers.contacts.companies.update.success') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/companies/1
  # DELETE /contacts/companies/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('controllers.contacts.companies.destroy.success') }
      format.json { head :no_content }
    end
  end

end

app/controllers/contacts/people_controller.rb
class Contacts::PeopleController < ContactsController

  # GET /contacts/people/1
  # GET /contacts/people/1.json
  def show
    @notes = @contact.notes
  end

  # GET /contacts/people/new
  def new
    @contact = Contacts::Person.new
    set_company
  end

  # GET /contacts/people/1/edit
  def edit
    set_company
  end

  # POST /contacts/people
  # POST /contacts/people.json
  def create
    @contact = Contacts::Person.new(contacts_person_params.merge(user: current_user))
    company = Contacts::Company.new(contacts_company_params.merge(user: current_user)) if params[:contacts_company]
    @contact.company = company if @contact.company.nil? && !company.nil? && company.valid?

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: t('controllers.contacts.people.create.success') }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/people/1
  # PATCH/PUT /contacts/people/1.json
  def update
    @contact.assign_attributes contacts_person_params

    company = Contacts::Company.new(contacts_company_params.merge(user: current_user)) if params[:contacts_company]
    @contact.company = company if @contact.company.nil? && !company.nil? && company.valid?

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: t('controllers.contacts.people.update.success') }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/people/1
  # DELETE /contacts/people/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('controllers.contacts.people.destroy.success') }
      format.json { head :no_content }
    end
  end

  private
  def set_company
    @companies = Contacts::Company.order(:name)
    @company = @contact.company || Contacts::Company.new
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = current_user.contacts

    @search_scope = (search_in_params?) ? params[:options][:search].to_s : nil
    @searchable_fields = %w(name first_name email activity)
    @search_field = if search_field_in_params? && @searchable_fields.include?(params[:options][:search_field].to_s)
                      params[:options][:search_field].to_sym
                    else
                      nil
                    end
    if @search_scope
      @contacts = (@search_field) ? @contacts.search(@search_scope, [@search_field]) : @contacts.search(@search_scope)
    end

    @selected_order = (order_in_params? && @searchable_fields.include?(params[:options][:order].to_s)) ? params[:options][:order].to_s : 'name'

    @sorts = %w(asc desc)
    @selected_sort = (sort_in_params? && @sorts.include?(params[:options][:sort].to_s)) ? params[:options][:sort].to_s : 'asc'

    #nullify empty string fields (but string type only)
    @contacts = if %w(name first_name email activity).include?(@selected_order)
                  @contacts.order("NULLIF(#{@selected_order},'') #{@selected_sort} NULLS LAST")
                else
                  @contacts.order("#{@selected_order} #{@selected_sort} NULLS LAST")
                end

    @contacts = @contacts.page(params[:page])
  end

  private
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contacts_company_params
    Contacts::Company.permits_params params.require(:contacts_company)
  end

  def contacts_person_params
    Contacts::Person.permits_params(params.require(:contacts_person))
  end

  def search_in_params?
    options_params? && params[:options][:search] && !params[:options][:search].blank?
  end

  def search_field_in_params?
    options_params? && params[:options][:search_field] && !params[:options][:search_field].blank?
  end

  def order_in_params?
    options_params? && params[:options][:order] && !params[:options][:order].blank?
  end

  def sort_in_params?
    options_params? && params[:options][:sort] && !params[:options][:sort].blank?
  end

  def options_params?
    params && params[:options]
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper

  def full_name contact
    full_name = contact.name
    full_name += " #{contact.first_name}" if contact.is_a?(Contacts::Person)
    full_name
  end

end

app/views/contacts/_notes_table.html.erb
<table class="table tablesorter">
  <thead>
  <tr>
    <th><%= t('views.contacts._notes_table.title') %></th>
    <th><%= t('views.contacts._notes_table.date') %></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% notes.each do |note| %>
      <tr>
        <td><%= link_to note.title, note %></td>
        <td><%= note.updated_at %></td>
        <td><%= actions_group edit_btn(edit_note_path(note)), delete_btn(note_path(note)) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/contacts/index.html.erb
<div class="content-box col-centered">
  <h2>Contacts</h2>

  <%= paginate @contacts %>
  <p class="pagination-total"><%= page_entries_info @contacts %></p>

  <div class="btn-group pull-right">
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
      <span class="glyphicon glyphicon-plus"></span>
    </button>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to t('views.contacts.index.new_person'), new_contacts_person_path %></li>
      <li><%= link_to t('views.contacts.index.new_company'), new_contacts_company_path %></li>
    </ul>
  </div>

  <%= simple_form_for(:options, method: :get, html: {class: 'filters_form'}) do |f| %>
      <%= f.input_field :search, required: false, value: @search_scope, placeholder: t('views.contacts.index.search') %>

      <% searchable_fields_collection = []
         @searchable_fields.each do |field|
           searchable_fields_collection << [t("views.contacts.index.searchable_fields.#{field}"), field]
         end
      %>
      <%= f.input_field :search_field, collection: searchable_fields_collection, selected: @search_field, include_blank: t('views.contacts.index.searchable_fields.all') %>

      <br/>
      <label class="select required" for="options_order"><%= t 'views.contacts.index.sort_by' %></label>
      <% sortable_fields_collection = []
         @searchable_fields.each do |field|
           sortable_fields_collection << [t("views.contacts.index.sortable_fields.#{field}"), field]
         end
      %>
      <%= f.input_field :order, collection: sortable_fields_collection, selected: @selected_order %>

      <% sort_scopes_collection = []
         @sorts.each do |scope|
           sort_scopes_collection << [t("views.contacts.index.sorts.#{scope}"), scope]
         end
      %>
      <%= f.input_field :sort, collection: sort_scopes_collection, selected: @selected_sort %>

<% end %>


  <table class="table pretty-table">
    <thead>
    <tr>
      <th><%= t('views.contacts.index.name') %></th>
      <th><%= t('views.contacts.index.first_name') %></th>
      <th><%= t('views.contacts.index.email') %></th>
      <th><%= t('views.contacts.index.activity') %></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @contacts.each do |contact| %>
        <tr>
          <td><%= link_to contact.name, contact %></td>
          <td><%= link_to(contact.first_name, contact) if contact.is_a?(Contacts::Person) %></td>
          <td><%= mail_to contact.email %></td>
          <td><%= mail_to contact.activity %></td>
          <td><%= actions_group delete_btn(url_for(contact)) %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <%= paginate @contacts %>
  <p class="pagination-total"><%= page_entries_info @contacts %></p>

</div>

app/views/contacts/show.html.erb
<div class="content-box col-centered">
  <h2>
    <%= full_name @contact %>
    <div class="btn-group pull-right">
      <a href="<%= new_note_for_contact_path(@contact) %>" class="btn btn-primary btn-xs">
        <span class="glyphicon glyphicon-plus"></span> <%= t('views.contacts.show.new_note') %>
      </a>
    </div>
  </h2>


  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#contact" aria-controls="contact" role="tab" data-toggle="tab"><%= t('views.contacts.show.tab_contact') %></a>
    </li>
    <li role="presentation">
      <a href="#notes" aria-controls="notes" role="tab" data-toggle="tab"><%= t('views.contacts.show.tab_notes') %></a>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="contact">
      <%= render @contact %>
    </div>
    <div role="tabpanel" class="tab-pane" id="notes">
      <%= render partial: 'contacts/notes_table', locals: {notes: @notes} %>
    </div>
  </div>
</div>